PORTNAME=	bombadillo
DISTVERSION=	2.4.0
CATEGORIES=	www
MASTER_SITES=	https://tildegit.org/sloum/bombadillo/archive/
DISTNAME=	${DISTVERSION}

MAINTAINER=	sage@anachronauts.club
COMMENT=	Non-web browser

LICENSE=	GPLv3

BUILD_DEPENDS=	go:lang/go

USES=		gmake
ALL_TARGET=	build
WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
