# $FreeBSD$

PORTNAME=	bombadillo
DISTVERSION=	2.3.3
CATEGORIES=	www
MASTER_SITES=	https://tildegit.org/sloum/bombadillo/archive/
DISTFILES=	${DISTVERSION}${EXTRACT_SUFX}
WRKSRC=		${WRKDIR}/${PORTNAME}

MAINTAINER=	sage@anachronauts.club
COMMENT=	A non-web browser

BUILD_DEPENDS=	go:lang/go
USES=		gmake
ALL_TARGET=	build

.include <bsd.port.mk>
